# Stage 1: Build dependencies

FROM node:18.12.1-alpine3.14 AS builder

WORKDIR /app

COPY package.json ./

RUN npm install --production

# Stage 2: Build production image

FROM nginx:stable-alpine

WORKDIR /app

COPY --from=builder /app/node_modules .
COPY . .

# Configure Nginx

RUN mv ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]